version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}-backend:${IMAGE_TAG}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=staging
      - DATABASE_URL=${STAGING_DATABASE_URL}
      - REDIS_URL=${STAGING_REDIS_URL}
      - JWT_SECRET=${STAGING_JWT_SECRET}
      - MINIO_ENDPOINT=${STAGING_MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${STAGING_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${STAGING_MINIO_SECRET_KEY}
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}-frontend:${IMAGE_TAG}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=staging
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${STAGING_POSTGRES_DB}
      - POSTGRES_USER=${STAGING_POSTGRES_USER}
      - POSTGRES_PASSWORD=${STAGING_POSTGRES_PASSWORD}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_staging_data:/data
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${STAGING_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${STAGING_MINIO_SECRET_KEY}
    volumes:
      - minio_staging_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.staging.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_staging_data:
  redis_staging_data:
  minio_staging_data:

networks:
  app-network:
    driver: bridge